/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ProyectoFinalVista;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import proyectofinal.Entidades.Inquilino;
import proyectofinal.Entidades.PropiedadInmueble;
import proyectofinal.Entidades.Propietario;
import proyectofinal.accesoADatos.Conexion;
import proyectofinal.accesoADatos.InquilinoData;
import proyectofinal.accesoADatos.PropiedadInmuebleData;
import proyectofinal.accesoADatos.PropietarioData;

/**
 *
 * @author MCali
 */
public class ModificarInmueble extends javax.swing.JInternalFrame {
    private Connection con = null;
    
    PropiedadInmuebleData propInmD = new PropiedadInmuebleData();
    
    /**
     * Creates new form ModificarInmueble
     */
    public ModificarInmueble() {
        
//        System.out.println("pi a modif:::"+propiInm);
        initComponents();
        con=Conexion.getConexion();
//        txtIdInm.enable(false);
//        txtPropietario.enable(false);
//        txtInquilino.enable(false);
//        cargarInmueble(propiInm);
//        cargar_cbPropietario();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoLocal = new javax.swing.JComboBox<>();
        lbPropietario = new javax.swing.JLabel();
        txtForma = new javax.swing.JTextField();
        lbForma = new javax.swing.JLabel();
        lbPrecioTazado = new javax.swing.JLabel();
        lbSuperficie = new javax.swing.JLabel();
        txtPrecioTazado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSuperficie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCaracteristicas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptarPropInm = new javax.swing.JButton();
        lbTipoLocal = new javax.swing.JLabel();
        lbIdInm = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbAccesibilidad = new javax.swing.JLabel();
        lbZona = new javax.swing.JLabel();
        txtIdInm = new javax.swing.JTextField();
        txtZona = new javax.swing.JTextField();
        txtAccesibilidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbCaracteristicas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbDireccion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        cbTipoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Casa", "Campo", "Local Comercial", "Galpon", "Garage" }));

        lbPropietario.setText("Propietario:");

        lbForma.setText("Forma");

        lbPrecioTazado.setText("Precio Tazado");

        lbSuperficie.setText("Superficie");

        jLabel13.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("jLabel2");

        jLabel15.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("jLabel2");

        jLabel16.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("jLabel2");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptarPropInm.setText("Aceptar");
        btnAceptarPropInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPropInmActionPerformed(evt);
            }
        });

        lbTipoLocal.setText("Tipo de Local");

        lbIdInm.setText("ID Nuevo Inmueble");

        jLabel18.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("jLabel2");

        lbAccesibilidad.setText("Accesibilidad");

        lbZona.setText("Zona");

        txtIdInm.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel20.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("jLabel2");

        lbCaracteristicas.setText("Caracteristicas");

        lbDireccion.setText("Direccion");

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("jLabel2");

        txtPropietario.setPreferredSize(new java.awt.Dimension(100, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPropietario)
                            .addComponent(lbIdInm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdInm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addComponent(txtPropietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrecioTazado)
                                    .addComponent(lbSuperficie)
                                    .addComponent(lbTipoLocal)
                                    .addComponent(lbZona))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel20)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrecioTazado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCaracteristicas)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(txtCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAccesibilidad)
                                    .addComponent(lbDireccion)
                                    .addComponent(lbForma))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtForma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtAccesibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAceptarPropInm)
                        .addGap(49, 49, 49)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdInm)
                    .addComponent(txtIdInm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPropietario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbAccesibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addComponent(txtAccesibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbForma, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtForma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecioTazado, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtPrecioTazado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoLocal)
                    .addComponent(cbTipoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbZona, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnAceptarPropInm))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarPropInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPropInmActionPerformed
        // TODO add your handling code here:
        try{
            int id = parseInt(txtIdInm.getText());
            String acces = txtAccesibilidad.getText();
            String carac = txtCaracteristicas.getText();
            String direc = txtDireccion.getText();
//            System.out.println(acces+carac+direc+"muestra a c d");
           
            int propid = Integer.parseInt(txtPropietario.getText());
            PropietarioData prop = new PropietarioData();
            Propietario p = new Propietario(prop.BuscarPropietarioID(propid).getIdPropietario(),prop.BuscarPropietarioID(propid).getApelidoPropietario(),prop.BuscarPropietarioID(propid).getNombrePropietario(),prop.BuscarPropietarioID(propid).getDni(),prop.BuscarPropietarioID(propid).getDomicilio(),prop.BuscarPropietarioID(propid).getTelefono());
            
            
//            int inquid =Integer.parseInt(txtInquilino.getText());
//            InquilinoData inq = new InquilinoData();
//            inq.BuscarInquilinoId(inquid);
            
            String forma = txtForma.getText();
            float precio = Float.parseFloat(txtPrecioTazado.getText());
            int superf = Integer.parseInt(txtSuperficie.getText()) ;
            String tipo = (String) cbTipoLocal.getSelectedItem();
            String zona = txtZona.getText();

            PropiedadInmueble propinm = new PropiedadInmueble(id,acces,carac,direc,p,true,forma,precio,superf,tipo,zona);
            propInmD.ModificarPropiedadInmueble(propinm);
            
//            System.out.println("prop inmueble a cargar: "+propinm);

        }catch(NumberFormatException E){
            JOptionPane.showMessageDialog(null, "Debe completar todas las casillas");
        }

    }//GEN-LAST:event_btnAceptarPropInmActionPerformed

     private void cargarInmueble(PropiedadInmueble propieInm){
        System.out.println("carga");
        txtIdInm.setText(propieInm.getID_Local()+"");
        txtAccesibilidad.setText(propieInm.getAccesibilidad());
        txtCaracteristicas.setText(propieInm.getCaracteristicas());
        txtDireccion.setText(propieInm.getDireccion());
        txtPropietario.setText(propieInm.getDuenio().getIdPropietario()+"");
//        txtInquilino.setText(propieInm.getOcupante().getId_Inquilino() +"");
        txtForma.setText(propieInm.getForma());
        txtPrecioTazado.setText(propieInm.getPrecioTazado()+"");
        txtSuperficie.setText(propieInm.getSuperficieMinima()+"");
        txtZona.setText(propieInm.getZona());
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        PropiedadInmuebleVista nombre = new PropiedadInmuebleVista();   
        JDesktopPane desktopPane = getDesktopPane(); 
        desktopPane.add(nombre);
        nombre.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

//     private void cargar_cbPropietario(){ //carga los comoboBox con dni y nombre de los propietario
//
//        
//        PropietarioData propD = new PropietarioData();
//        ArrayList<Propietario> propietario = new ArrayList<>();
//
//        for (Propietario prop : propD.obtenerLosPropietarios()) {
//            propietario.add(prop);
//           // cbPropietarios.addItem(prop.getDni()+" "+prop.getApelidoPropietario()+", "+prop.getNombrePropietario());
//            cbPropietarios.addItem(prop);
//        }
//
//    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPropInm;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbTipoLocal;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbAccesibilidad;
    private javax.swing.JLabel lbCaracteristicas;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbForma;
    private javax.swing.JLabel lbIdInm;
    private javax.swing.JLabel lbPrecioTazado;
    private javax.swing.JLabel lbPropietario;
    private javax.swing.JLabel lbSuperficie;
    private javax.swing.JLabel lbTipoLocal;
    private javax.swing.JLabel lbZona;
    private javax.swing.JTextField txtAccesibilidad;
    private javax.swing.JTextField txtCaracteristicas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtForma;
    private javax.swing.JTextField txtIdInm;
    private javax.swing.JTextField txtPrecioTazado;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtSuperficie;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
