package ProyectoFinalVista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinal.Entidades.PropiedadInmueble;
import proyectofinal.accesoADatos.Conexion;
import proyectofinal.accesoADatos.PropiedadInmuebleData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author MCali
 */
public class PropiedadInmuebleVista extends javax.swing.JInternalFrame {

    /*   */
    private Connection con= null;
    private DefaultTableModel modelo= new DefaultTableModel();
    /*   */
    

    public PropiedadInmuebleVista() {
        initComponents();
        con= Conexion.getConexion();
        cargarTabla();
        mostrarDatosPropiedadInmueble();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        backG = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnAgregarInmueble = new javax.swing.JButton();
        btnModificarInmueble = new javax.swing.JButton();
        btnEliminarInmueble = new javax.swing.JButton();
        btnAlquilarInmueble = new javax.swing.JButton();
        btnActualizarPrecio = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        rbInmDisponible = new javax.swing.JRadioButton();
        rbInmAlquilado = new javax.swing.JRadioButton();
        rbCasa = new javax.swing.JRadioButton();
        rbTerreno = new javax.swing.JRadioButton();
        rbLocalComercial = new javax.swing.JRadioButton();
        rbGalpon = new javax.swing.JRadioButton();
        rbGarage = new javax.swing.JRadioButton();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInmuebles = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion de Inmuebles");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        backG.setBackground(new java.awt.Color(255, 255, 255));
        backG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 570));

        btnAgregarInmueble.setText("Agregar");

        btnModificarInmueble.setText("Modificar");

        btnEliminarInmueble.setText("Eliminar");

        btnAlquilarInmueble.setText("Alquilar");

        btnActualizarPrecio.setText("Actualizar Precio");

        Grupo1.add(rbInmDisponible);
        rbInmDisponible.setText("Inmueble Disponible");

        Grupo1.add(rbInmAlquilado);
        rbInmAlquilado.setText("Inmuebles Alquilado");

        Grupo2.add(rbCasa);
        rbCasa.setText("Casa");

        Grupo2.add(rbTerreno);
        rbTerreno.setText("Terreno");

        Grupo2.add(rbLocalComercial);
        rbLocalComercial.setText("Local Comercial");

        Grupo2.add(rbGalpon);
        rbGalpon.setText("Galpon");

        Grupo2.add(rbGarage);
        rbGarage.setText("Garage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbGarage)
                            .addComponent(rbGalpon)
                            .addComponent(rbLocalComercial)
                            .addComponent(rbTerreno)
                            .addComponent(rbCasa)
                            .addComponent(rbInmAlquilado)
                            .addComponent(rbInmDisponible)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEliminarInmueble))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarInmueble)
                            .addComponent(btnModificarInmueble))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarPrecio)
                            .addComponent(btnAlquilarInmueble))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarInmueble)
                    .addComponent(btnAlquilarInmueble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarInmueble)
                    .addComponent(btnActualizarPrecio))
                .addGap(16, 16, 16)
                .addComponent(btnEliminarInmueble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbInmDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbInmAlquilado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTerreno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLocalComercial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbGalpon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbGarage)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        backG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        lbTitulo.setText("Propiedades");
        backG.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        tablaInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Accesibilidad", "Caracteristicas", "Direccion", "Precio", "Superficie", "Tipo", "Zona"
            }
        ));
        jScrollPane1.setViewportView(tablaInmuebles);
        if (tablaInmuebles.getColumnModel().getColumnCount() > 0) {
            tablaInmuebles.getColumnModel().getColumn(0).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaInmuebles.getColumnModel().getColumn(1).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(2).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(3).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(4).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(5).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(6).setResizable(false);
            tablaInmuebles.getColumnModel().getColumn(7).setResizable(false);
        }

        backG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void mostrarDatosPropiedadInmueble(){
        
        borrarFilas();
        lbTitulo.setText("Lista completa de propiedades");
        PropiedadInmuebleData id= new PropiedadInmuebleData();
        for(PropiedadInmueble prop:id.obtenerLasPropiedades()){                  
            System.out.println(prop);
            modelo.addRow(new Object []{prop.getID_Local(), prop.getAccesibilidad(),prop.getCaracteristicas(), prop.getDireccion(),prop.getPrecioTazado(),prop.getSuperficieMinima(),prop.getTipoLocal(),prop.getZona()});
            modelo.addRow(new Object []{2, "xx","ww", "ss",12000,20,"ee","q"});
        
        }
        
    }
    private void borrarFilas() {
        int f = tablaInmuebles.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    
    public void cargarTabla() {

        modelo.addColumn("id");
        modelo.addColumn("acc");
        modelo.addColumn("car");
        modelo.addColumn("dir");
        modelo.addColumn("pre");
        modelo.addColumn("suo");
        modelo.addColumn("tipo");
        modelo.addColumn("zona");

        tablaInmuebles.setModel(modelo);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.ButtonGroup Grupo2;
    private javax.swing.JPanel backG;
    private javax.swing.JButton btnActualizarPrecio;
    private javax.swing.JButton btnAgregarInmueble;
    private javax.swing.JButton btnAlquilarInmueble;
    private javax.swing.JButton btnEliminarInmueble;
    private javax.swing.JButton btnModificarInmueble;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rbCasa;
    private javax.swing.JRadioButton rbGalpon;
    private javax.swing.JRadioButton rbGarage;
    private javax.swing.JRadioButton rbInmAlquilado;
    private javax.swing.JRadioButton rbInmDisponible;
    private javax.swing.JRadioButton rbLocalComercial;
    private javax.swing.JRadioButton rbTerreno;
    private javax.swing.JTable tablaInmuebles;
    // End of variables declaration//GEN-END:variables
}
